version: '3.9'

services:
  mailer:
    build: .
    container_name: mailer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SMTP_HOST: smtp.example.com
      SMTP_PORT: "587"
      SMTP_USER: user@example.com
      SMTP_PASS: yourpassword
